import unreal as u
assert not u.get_editor_subsystem(u.LevelEditorSubsystem).is_in_play_in_editor()
assert not u.EditorLoadingAndSavingUtils.get_dirty_map_packages()
assert not u.EditorLoadingAndSavingUtils.get_dirty_content_packages()
world=u.EditorLoadingAndSavingUtils.new_blank_map(False)
world.get_world_settings().set_editor_property('default_game_mode',u.GameModeBase)
actors=u.get_editor_subsystem(u.EditorActorSubsystem)
camera_position=u.Vector(0,-750,600)
camera=actors.spawn_actor_from_class(u.CameraActor,camera_position,u.MathLibrary.find_look_at_rotation(camera_position,u.Vector(0,0,120)))
camera.set_actor_label('QTrailPreviewCamera')
light=actors.spawn_actor_from_class(u.DirectionalLight,u.Vector(0,0,700),u.Rotator(pitch=-60,yaw=-30,roll=0))
floor=actors.spawn_actor_from_class(u.StaticMeshActor,u.Vector(0,0,-30))
floor.static_mesh_component.set_static_mesh(u.load_asset('/Engine/BasicShapes/Plane'))
floor.set_actor_scale3d(u.Vector(40,40,1))
actors.spawn_actor_from_class(u.Champion_Ezreal,u.Vector(-900,500,120))
perf=u.get_default_object(u.load_class(None,'/Script/UnrealEd.EditorPerformanceSettings'))
perf.set_editor_property('bThrottleCPUWhenNotForeground',False)
u.get_editor_subsystem(u.LevelEditorSubsystem).editor_request_begin_play()
print('Q_PREVIEW_PIE_REQUESTED')
